version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["LambdaScraperFunction=390403871638.dkr.ecr.eu-west-3.amazonaws.com/samapp7427b055/lambdascraperfunction7a9f15afrepo"]
